// Generated by Wrangler on Fri May 31 2024 19:14:57 GMT+0200 (hora de verano de Europa central)
// by running `wrangler types`

interface Env {
	F1_CACHE: KVNamespace;
	XATA_API_KEY: string;
	XATA_BRANCH: string;
	XATA_DATABASE_URL: string;
}
